# -*- coding: utf-8 -*-
"""Pandas1.ipynb

Automatically generated by Colaboratory.

Original file is located at
    https://colab.research.google.com/drive/1fVsm1dMq857YFrn_G7i6TSxwekTxgM2l
"""

import pandas as pd
# df = pd.read_csv("/content/Temp_and_rain.csv")
df = pd.read_csv("/content/nyc_weather.csv");
df

# df["Temperature"].max()

# df['EST'][df['Events']=='Rain']

# df['WindSpeedMPH'].mean()

"""Process of cleaning messy data is called data munging or data wrangling"""

df.fillna(0,inplace=True)
df['WindSpeedMPH'].mean()